servers : 12
repl :
  - 'START'
  - 'EXIT'
clients:
  - client : 0
    msg :
      - 0
      - 16
      - 17
      - 18
  - client : 1
    msg :
      - 1
      - 19
  - client : 2
    msg :
      - 2
      - 20
      - 21
  - client : 3
    msg :
      - 3
      - 32
      - 38
  - client : 4
    msg :
      - 4
      - 42
      - 43
  - client : 5
    msg :
      - 5
      - 51
  - client : 6
    msg :
      - 6
      - 67
  - client : 7
    msg :
      - 7
      - 76
  - client : 8
    msg :
      - 8
      - 80
  - client : 9
    msg :
      - 9
      - 99
      - 9000
  - client : 10
    msg :
      - 10
  - client : 11
    msg :
      - 11
  - client : 12
    msg :
      - 12
  - client : 13
    msg :
      - 13
  - client : 14
    msg :
      - 14
  - client : 15
    msg :
      - 15
